language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  python model.py

services:
  - docker

before_install:
  - docker build -t chandan1653/loan-prediction-ml
  - docker ps -a
  - docker run chandan1653/loan-prediction-ml
  - docker ps -a